import css from './style.module.scss'

import type { Metadata } from 'next'

import '@/assets/styles/tailwind/index.scss'
import '@/assets/styles/main/index.scss'

import Controller from '@/components/Controller'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <Controller />
        <div id={css["app"]}>
          {children}
        </div>
      </body>
    </html>
  )
}
